# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4817659926f30bf256c2ac11db6bc41b113149e8477fde8fb9284261cec9d889fb5fb91b4372d2cecc49296c84921d96bdd40d43a547932d8ca7288dabc72e0b

test:
  secret_key_base: d1ed1ec58fcda9baf25826ad81624500f0cb91bc77e6f233a9bd0e8e16e25b54e2d12cd78915ce95a501845b14d55753a9b957981b8e9d44cf6a9638550ffeca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
